baseURL = "https://joeycarter.github.io"
languageCode = "en-us"
title = "Joey Carter"
theme = "para-minimal"
disqusShortname = "joeycarter"  # uncomment to enable disqus comments

[params]
    author = "Joey Carter"
    description = "University of Toronto"
    githubUsername = "joeycarter"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Open Sans"  # should match the name on Google Fonts!
    fontsize = "16px"
    highlight = true
    highlightStyle = "github"
    highlightLanguages = ["go", "python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/research/"
    name = "Research"
    weight = 2

[[menu.main]]
    url = "/cv/"
    name = "CV"
    weight = 3

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 4


# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:jcarter@physics.utoronto.ca"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/joeycarter/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://gitlab.cern.ch/jocarter"
    name = "gitlab"
    weight = 3

# [[menu.icon]]
#     url = "https://twitter.com/username/"
#     name = "twitter"
#     weight = 3

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
